spring:
  application:
    name: spring_cloud_eurekaServer
eureka:
  client:
    fetch-registry: true #是否需要从服务端获取注册信息
    register-with-eureka: true  #是否注册到当前服务
    service-url:
      defaultZone: http://eurekaServer2:31002/eureka/,http://${eureka.instance.hostname}:${server.port}/eureka/  #注册中心的集群配置
  instance:
    hostname: eurekaServer1 #当前服务的主机名
    instance-id: http://${eureka.instance.hostname}:${server.port}/eureka/   #当前注册中心服务的唯一id
  server:
    enable-self-preservation: false  #开启eureka的自我保护机制
server:
  port: 31001