spring:
  application:
    name: spring_cloud_eurekaClient
eureka:
  client:
    fetch-registry: true #是否需要从服务端获取注册信息
    register-with-eureka: true  #是否在注册中心进行注册
    serviceUrl:
      defaultZone: http://eurekaServer1:31001/eureka/,http://eurekaServer2:31002/eureka/   #注册中心的集群配置
  instance:
    hostname: localhost #当前服务的主机名
    instanceId: http://${eureka.instance.hostname}:${server.port}/eureka/   #当前注册中心服务的唯一id
server:
  port: 31003